### ISSUE TITLE
Request: put license to the repository

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [souramoo/unapkm#11]
Please Apache or similar?

**Comment by TPS** [comment]
@souramoo Great info @ https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository & http://choosealicense.com/

**Comment by AndroidDeveloperLB** [comment]
I like the one that just says "do whatever you wish with it" . I don't remember its name though, but it was funny.
BTW, TPS, can I please contact you? I have something important to tell you.

**Comment by souramoo** [comment]
I have added an Apache license as seems to be standard for open source java projects these days for the repo with the latest commit :)

**Comment by TPS** [comment]
> BTW, TPS, can I please contact you? I have something important to tell you.

@AndroidDeveloperLB I can't seem to find [any mutual messaging forum where 1 can DM](https://github.com/isaacs/github/issues/651).  Your best bet is to message me (same nick) via the [F-droid Forum](https://forum.f-droid.org/) or perhaps open an issue on 1 of your _private_ repos here.

**Comment by AndroidDeveloperLB** [comment]
Thank you very much.
What I wrote was a joke, BTW. I hope you are not offended.
