### ISSUE TITLE
Decrypto error

### ISSUE THREAD

**Issue by xballiet** [souramoo/unapkm#13]
Hello!

I have this error:
_**java.io.IOException: decrypto error
        at com.souramoo.unapkm.UnApkm$1.run(UnApkm.java:139)**_

when I want to unapkm this package: https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=1509707
that can be found here: https://www.apkmirror.com/apk/picsart/picsart-picsart/picsart-picsart-15-5-0-release/picsart-photo-editor-pic-video-collage-maker-15-5-0-android-apk-download/

Is it a problem with the apkm or is it encrypted in a new way?

Thanks a lot for your work!
Xavier

**Comment by iMiKED** [comment]
This file decrypts **without** any errors. As usual.
You should investigate more into your system/JAVA installation/environment/used tools.

**Comment by iMiKED** [comment]
> I have this error:
> _**java.io.IOException: decrypto error at com.souramoo.unapkm.UnApkm$1.run(UnApkm.java:139)**_
> 
> when I want to unapkm this package: https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=1509707
> that can be found here: https://www.apkmirror.com/apk/picsart/picsart-picsart/picsart-picsart-15-5-0-release/picsart-photo-editor-pic-video-collage-maker-15-5-0-android-apk-download/
> 
> Is it a problem with the apkm or is it encrypted in a new way?
> 
> Thanks a lot for your work!
> Xavier

This file decrypts **without** any errors. As usual.
You should investigate more into your system/JAVA installation/environment/used tools.

**Comment by xballiet** [comment]
Here is the version of JAVA I have on my work PC, is it the problem?

> C:\Users\******>java -version
> openjdk version "1.8.0_242"
> OpenJDK Runtime Environment Corretto-8.242.08.1 (build 1.8.0_242-b08)
> OpenJDK Server VM Corretto-8.242.08.1 (build 25.242-b08, mixed mode)

**Comment by iMiKED** [comment]
Maybe. You should use java not from JRE (author, somewhy, don't want to use JRE), but from JDK.
Like that:
```
java version "14.0.1" 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
```

**Comment by souramoo** [comment]
Just tested and the apkm file itself decrypts without errors for me :)

This error appears to happen most often when the file you provide to unapkm is corrupted/incomplete - can you please try downloading the file again and confirming that the file size is 45259399 bytes?

**Comment by xballiet** [comment]
Yes I confirm that the file has the same size:
![image](https://user-images.githubusercontent.com/5589530/92463803-998d0600-f1cc-11ea-95ec-6028b2ad80d8.png)

And for the JDK / JRE, could you confirm or infirm that my version is OK?

**Comment by xballiet** [comment]
I have tried again today, on the same PC (at the office) and it works now... I don't know why, but the restart has fixed the problem...  ;)

![image](https://media.giphy.com/media/DUtVdGeIU8lmo/source.gif)
