### ISSUE TITLE
Fdroid

### ISSUE THREAD

**Issue by Yannik** [souramoo/unapkm#8]
Could you submit this to fdroid? :-)

**Comment by liamcottle** [comment]
We are moving to standard zip files soon :)
https://github.com/android-police/apkmirror-public/issues/119#issuecomment-605518136

**Comment by Yannik** [comment]
Oops, I've just noticed this is just a jar and not an apk. I think I'll stop using apkmirror and use [apkpure.com](https://apkpure.com) and/or [apkdl.in](https://apkdl.in) instead anyway.
