### ISSUE TITLE
Please target JAVA version 52.0 instead of 53.0

### ISSUE THREAD

**Issue by MihirGosai** [souramoo/unapkm#9]
Exception in thread "main" java.lang.UnsupportedClassVersionError:
com/souramoo/unapkm/UnApkm has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by nepixl** [comment]
Why? Just update your Java? -This is an issue on your end.

Works fine here..
Nice work btw - ty!

**Comment by ghost** [comment]
Hey I have a same issue. I have the last version of Java 8.

**Comment by MihirGosai** [comment]
> Why? Just update your Java? -This is an issue on your end.
> 
> Works fine here..
> Nice work btw - ty!

Yes, nice work but it is my request because v52 will also work on v53. Can not upgrade my Java version nowadays.

**Comment by souramoo** [comment]
Hey all, thanks for the kind words!

This is a fairly simple one to fix and an oversight on my part to assume everyone's on the latest java, I have rebuilt it targeting java 6 so hopefully it should work on any system now :)

https://github.com/souramoo/unapkm/releases/download/v1.2/unapkm.jar
